[package]
name = "markdown"
version = "0.1.0"
authors = ["MhmCats <71032999+MhmCats@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.9"